### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by songjiahong** [ahmetb/cloud-run-static-outbound-ip#1]
When follow the steps, the service complains for some error as:
_[FATAL tini (2)] exec ./entrypoint.sh failed: Permission denied_

How could that be fixed?
Tried to add line to change the execution permission but it doesn't work.
`RUN chmod +x /app`

**Comment by BishiBosS96** [comment]
> Tried to add line to change the execution permission but it doesn't work.
> `RUN chmod +x /app`

That should work, however, this change has to be done from the host, that means, you create the entrypoint.sh in the same level of the directory and change the permission from there. When the docker is built and the files copied through the command COPY, the file should have the permissions already

**Comment by songjiahong** [comment]
Sorry for false alarm. No idea why it doesn't work at the first place. Yes, that line did work and I double checked in the docker image. Newbie to docker, a lot needs to learn. Thanks!
